services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile.fpm
    environment:
      PHP_IDE_CONFIG: 'serverName=stage'
    restart: unless-stopped
    #ports:
    #    - "9003:9003"

  nginx:
    restart: unless-stopped

  postgres:
    restart: unless-stopped
    ports:
      - '5432:5432'

  redis:
    restart: unless-stopped
    ports:
      - '6379:6379'
