services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: dev
      args:
        WWWUSER: ${WWWUSER:-1000}
        WWWGROUP: ${WWWGROUP:-1000}
    restart: always
    container_name: tako-app
    working_dir: /var/www
    volumes:
      # - .:/var/www:cached
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - postgres
      - redis
    networks:
      - tako-network

  nginx:
    image: nginx:alpine
    container_name: tako-nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      # - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tako-network

  postgres:
    image: postgres:18-alpine
    container_name: tako-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-tako_module}
      POSTGRES_USER: ${DB_USERNAME:-fantoca}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12341234}
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tako-network

  redis:
    image: redis:alpine
    container_name: tako-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - tako-network

volumes:
  pg_data:
  redis_data:

networks:
  tako-network:
    driver: bridge
